### ISSUE TITLE
extra line at the bottom of the status line

### ISSUE THREAD

**Issue by youyongsong** [caiogondim/maglev#16]
![](http://7ktoea.com1.z0.glb.clouddn.com/maglev_extra_bottom_line.png)        
Is there any way to remove it ?

**Comment by caiogondim** [comment]
I cannot reproduce it.

BTW, if you want the status bar on top, just set `set-option -g status-position top` on your `.tmux.conf`

**Comment by caiogondim** [comment]
Please, post your `.tmux.conf` so I can try to reproduce your error.
The **Installing** section was updated, so please try to follow the new process.

**Comment by youyongsong** [comment]
Thanks, I found it was a problem of my iterm2,  there there will be one line padding on the bottom when my iterm2 is fullscreen.
