### ISSUE TITLE
Fix issue with black divider in left segment

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/maglev#2]

**Comment by caiogondim** [comment]
![screen shot 2015-07-01 at 12 39 42](https://cloud.githubusercontent.com/assets/33044/8452798/590bb104-1fee-11e5-9521-05484c6483c4.png)

**Comment by AlexTes** [comment]
I still seem to have this issue.

![screen shot 2016-12-12 at 10 53 53](https://cloud.githubusercontent.com/assets/2011351/21094890/58a3f408-c059-11e6-9b7c-e6d81793f2db.png)
