### ISSUE TITLE
missing icons issue

### ISSUE THREAD

**Issue by mike3run** [caiogondim/maglev#22]
I don't know why I'm missing some characters 😢  please help

![captura de pantalla 2016-06-11 a las 9 46 23 p m](https://cloud.githubusercontent.com/assets/7088511/15988630/f95198d2-301d-11e6-934a-52dded179fc7.png)
![captura de pantalla 2016-06-11 a las 9 46 31 p m](https://cloud.githubusercontent.com/assets/7088511/15988631/f955013e-301d-11e6-8f65-722a88d9059a.png)

**Comment by mike3run** [comment]
nvm i got it 👍

**Comment by caiogondim** [comment]
@mike3run Could you explain the steps you took to resolve the issue?
It is important because this issue will be crawled by Google and your answer can help lots of people with the same problem.

**Comment by mike3run** [comment]
Sure thing the solution lied in getting a powerline compatible font then using is as a secondary font on iTerm like this 
![captura de pantalla 2016-06-12 a las 10 33 38 p m](https://cloud.githubusercontent.com/assets/7088511/15996530/d792c556-30ed-11e6-9efc-8cf31ee4b0b7.png)

**Comment by mike3run** [comment]
Bigger shot just in case anyone needs it :)

![captura de pantalla 2016-06-12 a las 10 34 47 p m](https://cloud.githubusercontent.com/assets/7088511/15996536/eb94c00e-30ed-11e6-8f10-38545831b936.png)

**Comment by caiogondim** [comment]
Thanks a lot for the clarification, @mike3run 
It is indeed a very common error =)
