### ISSUE TITLE
Disable CUP and battery

### ISSUE THREAD

**Issue by kepbod** [caiogondim/maglev#24]
How could I disable the CUP and battery labels. I don't want them.

**Comment by cyfyifanchen** [comment]
@caiogondim I updated Maglev to the latest to get rid of the Battery part, however the entire UI is gone. Instead, now I have the plain look. Any ideas?

**Comment by cyfyifanchen** [comment]
@kepbod use the following line of code to replace the original on line 148 should make the battery and CPU icons gone. However, this is just a hack, the PR that the owner committed is a much better fix, but I couldn't get working. 

`status_right="︎#[fg=$time_date_fg,nobold]#{prefix_highlight} $right_separator %R $right_separator %a %d %b #[fg=$host_bg]"`
