### ISSUE TITLE
Request: Specify which font and/or colorscheme is used in the screenshot

### ISSUE THREAD

**Issue by JakobGM** [caiogondim/maglev#29]
Hi,

It would be great if we could add which font and colorscheme which is used in order to produce the screenshot in the ˋREADMEˋ.

Thanks in advance!

**Comment by caiogondim** [comment]
Font: Source Code Pro + Nerd Font https://github.com/ryanoasis/nerd-fonts
Color scheme: Tomorrow Night Eighties
