### ISSUE TITLE
A sorlarized-light theme for maglev

### ISSUE THREAD

**Issue by yzlnew** [caiogondim/maglev#32]
Really like the bullet-style. But for people using light theme for terminal or vim the color theme doesn't match.

So here's a  [sorlarized-light fork](https://github.com/yzlnew/maglev-sorlarized-light)  for maglev if anyone is interested.

It looks like this ->

![snipaste_2018-05-17_11-04-12](https://user-images.githubusercontent.com/4904877/40154946-c0e37886-59c3-11e8-8461-48e18b51716c.png)

**Comment by caiogondim** [comment]
That's lovely.
Thanks a lot for that ❤️
