### ISSUE TITLE
CPU and battery don't work

### ISSUE THREAD

**Issue by gAmUssA** [caiogondim/maglev#7]
subj. see screenshot

![bug?](https://image_clips.s3.amazonaws.com/1._localhost__test__1_window_1_tmux_2015-08-18_23-20-35.png)

**Comment by randsonjs** [comment]
You're using ubuntu 14.04? On my notebook are not showing too!

**Comment by gAmUssA** [comment]
```
                 ###
               ####                   User: apple
               ###                    Hostname: localhost
       #######    #######             Distro: OS X 10.11
     ######################           Kernel: Darwin
    #####################             Uptime: 5 days 19:05
    ####################              Shell: /usr/local/bin/zsh
    ####################              Terminal: xterm-256color
    #####################             Packages: 177
     ######################           CPU: Intel Core i7-4960HQ CPU @ 2.60GHz
      ####################            Memory: 16 GB
        ################              Disk: 84%
         ####     #####
```

**Comment by caiogondim** [comment]
Inside the repo, can you see something inside the `plugins` folder?

**Comment by caiogondim** [comment]
I guess it is related go git submodules initialization.

**Comment by gAmUssA** [comment]
@caiogondim Thanks for suggestion.
I ran `git submodule init` followed by `git submodule update`.
Now it looks like this 
![screen shot 2015-08-24 at 10 13 09 pm](https://cloud.githubusercontent.com/assets/433085/9457104/595d0132-4aad-11e5-904a-1c1163cbf229.png)
CPU indicator is not on the same line with battery indicator

**Comment by caiogondim** [comment]
Hey guys, we are not using git submodules anymore.
Could you re-install and test if everything is ok?

**Comment by caiogondim** [comment]
And please, use the new README instructions.

**Comment by smbambling** [comment]
I'm also running OS X and don't see the cpu or battery displayed.

![screen shot 2015-12-18 at 8 11 45 am](https://cloud.githubusercontent.com/assets/487229/11897607/fda4b314-a55e-11e5-974a-6175249b5ae2.png)


```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F1509
```

**Comment by yifanchen** [comment]
For some reason, my config isn't working either. 
![image](https://cloud.githubusercontent.com/assets/2340896/12030915/e89c71de-adc2-11e5-9963-758ab3ea2d5d.png)

**Comment by smbambling** [comment]
I was able to work around this by manually setting the cpu and battery .tmux configs to run after tpm
 
```bash
run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tmux-cpu/cpu.tmux'
run '~/.tmux/plugins/tmux-battery/battery.tmux'
```

**Comment by yifanchen** [comment]
@smbambling nice, that works, thanks for the comment. Any idea why the icon of arrow isn't working(by the window name and CPU)? 
![image](https://cloud.githubusercontent.com/assets/2340896/12036116/46ea965c-ae00-11e5-8ae0-c6c4f8d4cfbb.png)

**Comment by smbambling** [comment]
@yifanchen: You are not using a patched font. Look at powerline patched fonts.  I recommend hack sourcefoundry.org/hack/

**Comment by yifanchen** [comment]
@smbambling: That's exactly what I am using. I have Hack working in zsh and vim bullettrain. For some reasons, coudn't make work with this Maglev theme.

**Comment by paanvaannd** [comment]
I'm having the same problem reported by @yifanchen and @smbambling, and am also running the latest release of OS X. I've added the three lines of code aforementioned to my `.tmux.conf` file but the Battery and CPU plugins seem to "crash" after running `tmux source .tmux.conf`, and they only work for about half a second before the plugins crash. I'm using Input Mono as my font on iTerm2 and have tried modifying various settings within iTerm preferences, none of which have helped so far.

I do not think that it is an issue with the font that I am using, as it is one of the recommended Poweline compatible fonts. However, I recently read issue #19 by @yifanchen and don't see the same settings options within my version of iTerm2 (2.1.4), so I am not entirely sure whether this is some Unicode issue or not. I'm bringing up this issue here instead of on that thread because my main issue is with the CPU and Battery displays not functioning, and I'm not sure whether that would have anything to do with the issue presented within issue #19. For reference, here is the Settings panel within iTerm 2.1.4:
![settings](https://cloud.githubusercontent.com/assets/16567134/12252980/c5aa7100-b8a1-11e5-984c-2c3ceb5c0856.png)

**Comment by yifanchen** [comment]
@paanvaannd try this:
https://github.com/SebastienElet/iterm2-borderless

**Comment by paanvaannd** [comment]
@yifanchen Thanks, I now have those options in my settings! I've switched over to Hack as well and changed my settings to the same that you have but the CPU and Battery are still not showing, so I don't think it's a problem with the font. I've outlined some more issues that maglev is presenting me in issue #15, so when you've got the time if you could check that out, any help would be appreciated.

One question related to this iTerm build: how do you drag the screen around if it's borderless? Do you just use it full screen the whole time?

**Comment by yifanchen** [comment]
@paanvaannd:
try this:

For me it works if i place the mouse on the top border so that the scale icon shows, and move 1-2 pixels up before i drag. Or if you're on a MacBook, just use 3-finger-drag on trackpad.

**Comment by caiogondim** [comment]
As suggested by @marzk, just put `'caiogondim/maglev'` as the second item on `.tmux.conf`
```
# List of plugins
set -g @tpm_plugins '                \
    caiogondim/maglev                \
    tmux-plugins/tpm                 \
    tmux-plugins/tmux-sensible       \
    tmux-plugins/tmux-resurrect      \
    tmux-plugins/tmux-continuum      \
    tmux-plugins/tmux-yank           \
    tmux-plugins/tmux-pain-control   \
    tmux-plugins/tmux-copycat        \
    tmux-plugins/tmux-open           \
    tmux-plugins/tmux-battery        \
    tmux-plugins/tmux-cpu            \
'
```

New **Installing** instructions were updated https://github.com/caiogondim/maglev#installing

**Comment by paanvaannd** [comment]
Thanks for the info, @yifanchen!
